### ISSUE TITLE
被标题吸引了，没看懂怎么用呀，有没有更具体的代码呀？

### ISSUE THREAD

**Issue by bigccc** [JacksonBruce/FileServices#1]
**被标题吸引了，没看懂怎么用呀，有没有更具体的代码呀？**

还有还有请问回调该怎么用呢？

**Comment by JacksonBruce** [comment]
项目TestWeb目录下有演示代码
后端配置看：TestWeb/Startup.cs 文件
前端看：TestWeb/wwwroot/test.html 文件
前端使用代码：

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <a id="btnUp" href="#">上传</a>
    <script src="lib/jquery/dist/jquery.min.js"></script>
    <script src="lib/h5Uploader/Uploader.dev.js"></script>
    
    <script>
        var times={};
        var uploader = new Uploader({
            url: "/FileServices/Uploader",
            placeholder: "#btnUp",
            params: { dir: "test/kkk" },
            dragable: true
        });
        uploader.on({
            "error": function (file, arg) {
                arg.cancel = true;
                console.log("error:" + arg.message);
                console.log("resumableKey:",this.resumableKey);
            },
            "upload": function (file) {
                times[file.name] = new Date();
            },
            "success": function (file, arg) {
                var s = new Date() - times[file.name]
                console.log("成功返回结果用时：" + (s / 1000 / 60) + "分钟");
                console.log("返回结果：" + arg.result);
            },
            "complete": function (file) {
                var s = new Date() - times[file.name]
                console.log("上传文件“" + file.name + "”用时：" + (s / 1000 / 60) + "分钟");
            }
        })
    </script>
</body>
</html>

**Comment by JacksonBruce** [comment]
> **被标题吸引了，没看懂怎么用呀，有没有更具体的代码呀？**
> 
> 还有还有请问回调该怎么用呢？
